In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory
with_ppg=[]
import os
for dirname, _, filenames in os.walk('/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/Challenge2015_csv/'):
    for filename in filenames:
        if(filename!="ALARMS"):
            if("PLETH" in pd.read_csv(dirname+filename).columns):
                with_ppg.append(filename[0:-4])

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

df=pd.read_csv("/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/Challenge2015_csv/ALARMS", names=["Sample", "Label", "TrueAlarm"])
df_relevant=df.loc[df["Label"]!="Asystole"].copy()
df_relevant

df_filtered=df_relevant.loc[df_relevant["Sample"].isin(with_ppg)].copy()

df_filtered["Path"]=["/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/Challenge2015_csv/"+x+".csv" for x in df_filtered["Sample"]]
df_filtered

,Sample,Label,TrueAlarm,Path
0,v100s,Ventricular_Tachycardia,0,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...
1,v101l,Ventricular_Tachycardia,0,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...
2,v102s,Ventricular_Tachycardia,0,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...
6,t106s,Tachycardia,1,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...
7,t107l,Tachycardia,1,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...
...,...,...,...,...
740,b840s,Bradycardia,1,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...
743,v843l,Ventricular_Tachycardia,0,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...
746,v846s,Ventricular_Tachycardia,0,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...
748,v848s,Ventricular_Tachycardia,0,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...
749,b849l,Bradycardia,0,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...

In [4]:
afib_paths=[]
healthy_paths=[]
afib_samples=[]
healthy_samples=[]

for dirname, _, filenames in os.walk('/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv'):
    for filename in filenames:
        if("csv" in filename):
            afib_paths.append(dirname+"/"+filename)
            filename_split=filename.split("_")
            afib_samples.append(filename_split[2]+"_"+filename_split[3])

for dirname, _, filenames in os.walk('/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_non_af_csv'):
    for filename in filenames:
        if("csv" in filename):
            healthy_paths.append(dirname+"/"+filename)
            filename_split=filename.split("_")
            healthy_samples.append(filename_split[2]+"_"+filename_split[3]+"_"+filename_split[4])


afib_df=pd.DataFrame({"Sample":afib_samples,
        "Label":19*["Atrial_Fibrillation"],
        "TrueAlarm":19*[True],
        "Path":afib_paths})

healthy_df=pd.DataFrame({"Sample":healthy_samples,
        "Label":16*["Healthy"],
        "TrueAlarm":16*[True],
        "Path":healthy_paths})

df_filtered=pd.concat([df_filtered, afib_df, healthy_df])
df_filtered

,Sample,Label,TrueAlarm,Path
0,v100s,Ventricular_Tachycardia,0,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...
1,v101l,Ventricular_Tachycardia,0,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...
2,v102s,Ventricular_Tachycardia,0,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...
6,t106s,Tachycardia,1,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...
7,t107l,Tachycardia,1,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...
...,...,...,...,...
11,non_af_006,Healthy,1,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...
12,non_af_010,Healthy,1,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...
13,non_af_011,Healthy,1,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...
14,non_af_016,Healthy,1,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...
15,non_af_001,Healthy,1,/Users/sarahalabdulrazzak/Desktop/Capstone/mye...

In [5]:
import numpy as np
import pandas as pd
from scipy.interpolate import interp1d

def check_and_resample(file_path):
    if 'Challenge2015' in file_path:
        fs_original = 250
        target_fs = 125
        resample_needed = True
    elif 'mimic' in file_path.lower():
        fs_original = 125
        target_fs = 125
        resample_needed = False
    else:
        raise ValueError("Unknown source for file: " + file_path)
    
    print(f"{file_path}: Original sampling rate = {fs_original} Hz")

    # Load the data
    df = pd.read_csv(file_path)

    if not resample_needed:
        print("  Signal is already at 125 Hz — no resampling needed.")
        return df
    
    # Resample if needed
    print(f"  Resampling from {fs_original} Hz to {target_fs} Hz...")

    if 'PLETH' in df.columns:
        signal = df['PLETH'].values
    else:
        raise ValueError("PLETH column not found in the data.")

    # Create new time points
    original_time = np.arange(len(signal)) / fs_original
    new_time = np.arange(0, original_time[-1], 1/target_fs)

    # Interpolate
    interp_function = interp1d(original_time, signal, kind='linear')
    new_signal = interp_function(new_time)

    # Create a new DataFrame for the resampled signal
    df_resampled = pd.DataFrame(new_signal, columns=['PLETH'])

    print("  Resampling complete.")
    return df_resampled

In [6]:
chunk_len=1024

def standardize(data):
    return ( data - np.mean(data) ) / np.std(data)

def getWaveform(label, index, sampleType, startPoint=0, duration=chunk_len, trueAlarm=1):
    if label in ["Atrial_Fibrillation", "Healthy"]:
        file_path = df_filtered.loc[
            (df_filtered["Label"] == label) & (df_filtered["TrueAlarm"] == trueAlarm), 
            "Path"
        ].values[index]
        
        # First load and resample the file
        df = check_and_resample(file_path)
        
        # Then extract the signal after resampling
        if sampleType in df.columns:
            signal = df[sampleType].values[startPoint:startPoint + int(duration/2)]
            return standardize(signal)
        else:
            raise ValueError(f"{sampleType} column not found in file.")
    
    else:
        if sampleType == "ECG":
            sampleType = "II"
        elif sampleType == "PPG":
            sampleType = "PLETH"
        
        file_path = df_filtered.loc[
            (df_filtered["Label"] == label) & (df_filtered["TrueAlarm"] == trueAlarm), 
            "Path"
        ].values[index]

        try:
            signal = pd.read_csv(file_path)[sampleType].values[startPoint:startPoint + duration]
        except:
            signal = pd.read_csv(file_path)["V"].values[startPoint:startPoint + duration]
        
        return standardize(signal)

In [ ]:
import matplotlib.pyplot as plt
 
plt.plot(getWaveform("Atrial_Fibrillation", 0, "ECG"))

In [ ]:
plt.plot(getWaveform("Atrial_Fibrillation", 0, "PPG"))

In [7]:
def getWaveforms(label, index, sampleType, duration=chunk_len, trueAlarm=1):
    # Get the file path for the specified label, index, and trueAlarm
    file_path = df_filtered.loc[
        (df_filtered["Label"] == label) & (df_filtered["TrueAlarm"] == trueAlarm), 
        "Path"
    ].values[index]
    
    print(f"Loading file: {file_path}")

    # Handle sampleType consistency
    if sampleType == "ECG":
        sampleType = "II"
    elif sampleType == "PPG":
        sampleType = "PLETH"
    
    # Load and resample if necessary
    try:
        # Resample the data if needed
        df = check_and_resample(file_path)
        
        # Print the available columns to help debug if sampleType is not found
        print(f"Available columns: {df.columns.tolist()}")
        
        # If II column isn't found, check for "ECG" column
        if sampleType == "II" and "ECG" in df.columns:
            print("Warning: 'II' column not found. Falling back to 'ECG' column.")
            sampleType = "ECG"  # Use 'ECG' instead of 'II'
        
        # Check if the column exists after fallback
        if sampleType not in df.columns:
            print(f"Warning: {sampleType} column not found in file. Returning empty list.")
            return []
        
        fullWaveform = df[sampleType].values
        print(f"Loaded {len(fullWaveform)} samples from {sampleType}.")
    except Exception as e:
        print(f"Error loading file {file_path}: {e}")
        return []

    # Ensure there is enough data to split into chunks of the specified duration
    if len(fullWaveform) < duration:
        print(f"Warning: Not enough data to create a full chunk of size {duration}.")
        return []

    # Split into periods of specified length (duration)
    periodsList = [
        fullWaveform[i * duration : (i + 1) * duration] 
        for i in range(int(np.floor(len(fullWaveform) / duration)))
    ]
    
    print(f"Created {len(periodsList)} chunks of size {duration}.")
    
    return periodsList

In [ ]:
periods = getWaveforms("Atrial_Fibrillation", 0, "ECG")
if periods:  # Only try to plot if periods are found
    for i in range(min(10, len(periods))):
        plt.plot(periods[i])
        plt.show()
else:
    print("No valid periods found.")

In [15]:
import os
import pandas as pd
import numpy as np

# Define the output folder path
output_folder = "/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/"

# List of arrhythmia types you want to extract
arrhythmia_types = [
    "Ventricular_Flutter_Fib", "Ventricular_Tachycardia", "Tachycardia", "Bradycardia", 
    "Atrial_Fibrillation", "Healthy"
]

# Helper function to create directories if they don't exist
def create_dir(path):
    if not os.path.exists(path):
        os.makedirs(path)

# Helper function to write CSV data to a file
def write_csv(data, output_path):
    data.to_csv(output_path, index=False)
    print(f"Saved to {output_path}")

In [ ]:
for arrhythmia in arrhythmia_types:
    df_filtered_arrhythmia = df_filtered[df_filtered["Label"] == arrhythmia].copy()

    print(f"Processing {arrhythmia} samples. Number of samples: {len(df_filtered_arrhythmia)}")

    for idx in range(len(df_filtered_arrhythmia)):
        row = df_filtered_arrhythmia.iloc[idx]
        print(f"Processing row {idx} - Sample: {row['Sample']}, Path: {row['Path']}")

        try:
            # Extract ECG and PPG signals using the `getWaveform` function
            ecg_signal = getWaveform(arrhythmia, idx, "ECG", trueAlarm=1)
            ppg_signal = getWaveform(arrhythmia, idx, "PPG", trueAlarm=1)

            # Combine ECG and PPG signals into a single DataFrame
            combined_data = pd.DataFrame({
                'ECG': ecg_signal,
                'PPG': ppg_signal
            })

            # Define the patient's file name based on the sample
            patient_file = f"{row['Sample']}.csv"
            patient_output_path = os.path.join(arrhythmia_folder, patient_file)

            # Write the combined ECG and PPG data to CSV
            write_csv(combined_data, patient_output_path)

        except Exception as e:
            print(f"Error processing sample {row['Sample']} for {arrhythmia}: {e}")

Processing Ventricular_Flutter_Fib samples. Number of samples: 47
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Flutter_Fib/f120s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Flutter_Fib/f121l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Flutter_Fib/f129l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Flutter_Fib/f130s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Flutter_Fib/f137l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Flutter_Fib/f138s.csv
Error processing sample f144s for Ventricular_Flutter_Fib: index 6 is out of bounds for axis 0 with size 6
Error processing sample f189l for Ventricular_Flutter_Fib: index 7 is out of bounds for axis 0 with size 6
Error processing sample f190s for Ventricular_Flutter_Fib: index 8 is out of bounds for axis 0 with size 6
Error processing sample f260s for Ventricular_Flutter_Fib: index 9 is out of bounds for axis 0 with size 6
Error processing sample f261l for Ventricular_Flutter_Fib: index 10 is out of bounds for axis 0 with size 6
Error processing sample f281l for Ventricular_Flutter_Fib: index 11 is out of bounds for axis 0 with size 6
Error processing sample f304s for Ventricular_Flutter_Fib: index 12 is out of bounds for axis 0 with size 6
Error processing sample f321l for Ventricular_Flutter_Fib: index 13 is out of bounds for axis 0 with size 6
Error processing sample f346s for Ventricular_Flutter_Fib: index 14 is out of bounds for axis 0 with size 6
Error processing sample f352s for Ventricular_Flutter_Fib: index 15 is out of bounds for axis 0 with size 6
Error processing sample f362s for Ventricular_Flutter_Fib: index 16 is out of bounds for axis 0 with size 6
Error processing sample f407l for Ventricular_Flutter_Fib: index 17 is out of bounds for axis 0 with size 6
Error processing sample f408s for Ventricular_Flutter_Fib: index 18 is out of bounds for axis 0 with size 6
Error processing sample f414s for Ventricular_Flutter_Fib: index 19 is out of bounds for axis 0 with size 6
Error processing sample f415l for Ventricular_Flutter_Fib: index 20 is out of bounds for axis 0 with size 6
Error processing sample f450s for Ventricular_Flutter_Fib: index 21 is out of bounds for axis 0 with size 6
Error processing sample f474s for Ventricular_Flutter_Fib: index 22 is out of bounds for axis 0 with size 6
Error processing sample f499l for Ventricular_Flutter_Fib: index 23 is out of bounds for axis 0 with size 6
Error processing sample f500s for Ventricular_Flutter_Fib: index 24 is out of bounds for axis 0 with size 6
Error processing sample f529l for Ventricular_Flutter_Fib: index 25 is out of bounds for axis 0 with size 6
Error processing sample f543l for Ventricular_Flutter_Fib: index 26 is out of bounds for axis 0 with size 6
Error processing sample f544s for Ventricular_Flutter_Fib: index 27 is out of bounds for axis 0 with size 6
Error processing sample f545l for Ventricular_Flutter_Fib: index 28 is out of bounds for axis 0 with size 6
Error processing sample f563l for Ventricular_Flutter_Fib: index 29 is out of bounds for axis 0 with size 6
Error processing sample f586s for Ventricular_Flutter_Fib: index 30 is out of bounds for axis 0 with size 6
Error processing sample f593l for Ventricular_Flutter_Fib: index 31 is out of bounds for axis 0 with size 6
Error processing sample f602s for Ventricular_Flutter_Fib: index 32 is out of bounds for axis 0 with size 6
Error processing sample f605l for Ventricular_Flutter_Fib: index 33 is out of bounds for axis 0 with size 6
Error processing sample f610s for Ventricular_Flutter_Fib: index 34 is out of bounds for axis 0 with size 6
Error processing sample f613l for Ventricular_Flutter_Fib: index 35 is out of bounds for axis 0 with size 6
Error processing sample f618s for Ventricular_Flutter_Fib: index 36 is out of bounds for axis 0 with size 6
Error processing sample f637l for Ventricular_Flutter_Fib: index 37 is out of bounds for axis 0 with size 6
Error processing sample f642s for Ventricular_Flutter_Fib: index 38 is out of bounds for axis 0 with size 6
Error processing sample f657l for Ventricular_Flutter_Fib: index 39 is out of bounds for axis 0 with size 6
Error processing sample f691l for Ventricular_Flutter_Fib: index 40 is out of bounds for axis 0 with size 6
Error processing sample f697l for Ventricular_Flutter_Fib: index 41 is out of bounds for axis 0 with size 6
Error processing sample f768s for Ventricular_Flutter_Fib: index 42 is out of bounds for axis 0 with size 6
Error processing sample f789l for Ventricular_Flutter_Fib: index 43 is out of bounds for axis 0 with size 6
Error processing sample f792s for Ventricular_Flutter_Fib: index 44 is out of bounds for axis 0 with size 6
Error processing sample f799l for Ventricular_Flutter_Fib: index 45 is out of bounds for axis 0 with size 6
Error processing sample f829l for Ventricular_Flutter_Fib: index 46 is out of bounds for axis 0 with size 6
Processing Ventricular_Tachycardia samples. Number of samples: 284
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v100s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v101l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v102s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v111l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v113l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v115l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v119l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v122s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v127l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v128s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v132s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v135l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v136s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v139l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v140s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v141l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v143l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v146s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v147l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v148s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v153l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v154s.csv

/var/folders/87/1x2ps50d7dx1y569r31__0t00000gn/T/ipykernel_15915/973443539.py:4: RuntimeWarning: invalid value encountered in divide
  return ( data - np.mean(data) ) / np.std(data)

Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v155l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v158s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v159l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v160s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v162s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v164s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v166s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v168s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v169l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v176s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v177l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v179l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v180s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v181l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v182s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v188s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v194s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v198s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v199l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v200s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v201l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v202s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v204s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v205l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v206s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v207l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v210s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v211l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v212s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v217l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v218s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v221l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v222s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v224s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v230s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v232s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v233l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v241l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Ventricular_Tachycardia/v242s.csv
Error processing sample v243l for Ventricular_Tachycardia: index 61 is out of bounds for axis 0 with size 61
Error processing sample v244s for Ventricular_Tachycardia: index 62 is out of bounds for axis 0 with size 61
Error processing sample v245l for Ventricular_Tachycardia: index 63 is out of bounds for axis 0 with size 61
Error processing sample v246s for Ventricular_Tachycardia: index 64 is out of bounds for axis 0 with size 61
Error processing sample v247l for Ventricular_Tachycardia: index 65 is out of bounds for axis 0 with size 61
Error processing sample v248s for Ventricular_Tachycardia: index 66 is out of bounds for axis 0 with size 61
Error processing sample v250s for Ventricular_Tachycardia: index 67 is out of bounds for axis 0 with size 61
Error processing sample v253l for Ventricular_Tachycardia: index 68 is out of bounds for axis 0 with size 61
Error processing sample v254s for Ventricular_Tachycardia: index 69 is out of bounds for axis 0 with size 61
Error processing sample v255l for Ventricular_Tachycardia: index 70 is out of bounds for axis 0 with size 61
Error processing sample v256s for Ventricular_Tachycardia: index 71 is out of bounds for axis 0 with size 61
Error processing sample v257l for Ventricular_Tachycardia: index 72 is out of bounds for axis 0 with size 61
Error processing sample v258s for Ventricular_Tachycardia: index 73 is out of bounds for axis 0 with size 61
Error processing sample v259l for Ventricular_Tachycardia: index 74 is out of bounds for axis 0 with size 61
Error processing sample v262s for Ventricular_Tachycardia: index 75 is out of bounds for axis 0 with size 61
Error processing sample v271l for Ventricular_Tachycardia: index 76 is out of bounds for axis 0 with size 61
Error processing sample v274s for Ventricular_Tachycardia: index 77 is out of bounds for axis 0 with size 61
Error processing sample v275l for Ventricular_Tachycardia: index 78 is out of bounds for axis 0 with size 61
Error processing sample v280s for Ventricular_Tachycardia: index 79 is out of bounds for axis 0 with size 61
Error processing sample v282s for Ventricular_Tachycardia: index 80 is out of bounds for axis 0 with size 61
Error processing sample v291l for Ventricular_Tachycardia: index 81 is out of bounds for axis 0 with size 61
Error processing sample v292s for Ventricular_Tachycardia: index 82 is out of bounds for axis 0 with size 61
Error processing sample v293l for Ventricular_Tachycardia: index 83 is out of bounds for axis 0 with size 61
Error processing sample v298s for Ventricular_Tachycardia: index 84 is out of bounds for axis 0 with size 61
Error processing sample v303l for Ventricular_Tachycardia: index 85 is out of bounds for axis 0 with size 61
Error processing sample v307l for Ventricular_Tachycardia: index 86 is out of bounds for axis 0 with size 61
Error processing sample v309l for Ventricular_Tachycardia: index 87 is out of bounds for axis 0 with size 61
Error processing sample v312s for Ventricular_Tachycardia: index 88 is out of bounds for axis 0 with size 61
Error processing sample v316s for Ventricular_Tachycardia: index 89 is out of bounds for axis 0 with size 61
Error processing sample v317l for Ventricular_Tachycardia: index 90 is out of bounds for axis 0 with size 61
Error processing sample v318s for Ventricular_Tachycardia: index 91 is out of bounds for axis 0 with size 61
Error processing sample v319l for Ventricular_Tachycardia: index 92 is out of bounds for axis 0 with size 61
Error processing sample v322s for Ventricular_Tachycardia: index 93 is out of bounds for axis 0 with size 61
Error processing sample v323l for Ventricular_Tachycardia: index 94 is out of bounds for axis 0 with size 61
Error processing sample v324s for Ventricular_Tachycardia: index 95 is out of bounds for axis 0 with size 61
Error processing sample v325l for Ventricular_Tachycardia: index 96 is out of bounds for axis 0 with size 61
Error processing sample v326s for Ventricular_Tachycardia: index 97 is out of bounds for axis 0 with size 61
Error processing sample v327l for Ventricular_Tachycardia: index 98 is out of bounds for axis 0 with size 61
Error processing sample v336s for Ventricular_Tachycardia: index 99 is out of bounds for axis 0 with size 61
Error processing sample v337l for Ventricular_Tachycardia: index 100 is out of bounds for axis 0 with size 61
Error processing sample v338s for Ventricular_Tachycardia: index 101 is out of bounds for axis 0 with size 61
Error processing sample v347l for Ventricular_Tachycardia: index 102 is out of bounds for axis 0 with size 61
Error processing sample v348s for Ventricular_Tachycardia: index 103 is out of bounds for axis 0 with size 61
Error processing sample v353l for Ventricular_Tachycardia: index 104 is out of bounds for axis 0 with size 61
Error processing sample v354s for Ventricular_Tachycardia: index 105 is out of bounds for axis 0 with size 61
Error processing sample v355l for Ventricular_Tachycardia: index 106 is out of bounds for axis 0 with size 61
Error processing sample v361l for Ventricular_Tachycardia: index 107 is out of bounds for axis 0 with size 61
Error processing sample v364s for Ventricular_Tachycardia: index 108 is out of bounds for axis 0 with size 61
Error processing sample v365l for Ventricular_Tachycardia: index 109 is out of bounds for axis 0 with size 61
Error processing sample v366s for Ventricular_Tachycardia: index 110 is out of bounds for axis 0 with size 61
Error processing sample v367l for Ventricular_Tachycardia: index 111 is out of bounds for axis 0 with size 61
Error processing sample v368s for Ventricular_Tachycardia: index 112 is out of bounds for axis 0 with size 61
Error processing sample v369l for Ventricular_Tachycardia: index 113 is out of bounds for axis 0 with size 61
Error processing sample v370s for Ventricular_Tachycardia: index 114 is out of bounds for axis 0 with size 61
Error processing sample v371l for Ventricular_Tachycardia: index 115 is out of bounds for axis 0 with size 61
Error processing sample v373l for Ventricular_Tachycardia: index 116 is out of bounds for axis 0 with size 61
Error processing sample v374s for Ventricular_Tachycardia: index 117 is out of bounds for axis 0 with size 61
Error processing sample v375l for Ventricular_Tachycardia: index 118 is out of bounds for axis 0 with size 61
Error processing sample v380s for Ventricular_Tachycardia: index 119 is out of bounds for axis 0 with size 61
Error processing sample v381l for Ventricular_Tachycardia: index 120 is out of bounds for axis 0 with size 61
Error processing sample v390s for Ventricular_Tachycardia: index 121 is out of bounds for axis 0 with size 61
Error processing sample v392s for Ventricular_Tachycardia: index 122 is out of bounds for axis 0 with size 61
Error processing sample v395l for Ventricular_Tachycardia: index 123 is out of bounds for axis 0 with size 61
Error processing sample v398s for Ventricular_Tachycardia: index 124 is out of bounds for axis 0 with size 61
Error processing sample v399l for Ventricular_Tachycardia: index 125 is out of bounds for axis 0 with size 61
Error processing sample v400s for Ventricular_Tachycardia: index 126 is out of bounds for axis 0 with size 61
Error processing sample v401l for Ventricular_Tachycardia: index 127 is out of bounds for axis 0 with size 61
Error processing sample v402s for Ventricular_Tachycardia: index 128 is out of bounds for axis 0 with size 61
Error processing sample v403l for Ventricular_Tachycardia: index 129 is out of bounds for axis 0 with size 61
Error processing sample v404s for Ventricular_Tachycardia: index 130 is out of bounds for axis 0 with size 61
Error processing sample v405l for Ventricular_Tachycardia: index 131 is out of bounds for axis 0 with size 61
Error processing sample v419l for Ventricular_Tachycardia: index 132 is out of bounds for axis 0 with size 61
Error processing sample v421l for Ventricular_Tachycardia: index 133 is out of bounds for axis 0 with size 61
Error processing sample v423l for Ventricular_Tachycardia: index 134 is out of bounds for axis 0 with size 61
Error processing sample v426s for Ventricular_Tachycardia: index 135 is out of bounds for axis 0 with size 61
Error processing sample v427l for Ventricular_Tachycardia: index 136 is out of bounds for axis 0 with size 61
Error processing sample v431l for Ventricular_Tachycardia: index 137 is out of bounds for axis 0 with size 61
Error processing sample v432s for Ventricular_Tachycardia: index 138 is out of bounds for axis 0 with size 61
Error processing sample v433l for Ventricular_Tachycardia: index 139 is out of bounds for axis 0 with size 61
Error processing sample v437l for Ventricular_Tachycardia: index 140 is out of bounds for axis 0 with size 61
Error processing sample v438s for Ventricular_Tachycardia: index 141 is out of bounds for axis 0 with size 61
Error processing sample v448s for Ventricular_Tachycardia: index 142 is out of bounds for axis 0 with size 61
Error processing sample v452s for Ventricular_Tachycardia: index 143 is out of bounds for axis 0 with size 61
Error processing sample v453l for Ventricular_Tachycardia: index 144 is out of bounds for axis 0 with size 61
Error processing sample v454s for Ventricular_Tachycardia: index 145 is out of bounds for axis 0 with size 61
Error processing sample v460s for Ventricular_Tachycardia: index 146 is out of bounds for axis 0 with size 61
Error processing sample v464s for Ventricular_Tachycardia: index 147 is out of bounds for axis 0 with size 61
Error processing sample v466s for Ventricular_Tachycardia: index 148 is out of bounds for axis 0 with size 61
Error processing sample v470s for Ventricular_Tachycardia: index 149 is out of bounds for axis 0 with size 61
Error processing sample v471l for Ventricular_Tachycardia: index 150 is out of bounds for axis 0 with size 61
Error processing sample v472s for Ventricular_Tachycardia: index 151 is out of bounds for axis 0 with size 61
Error processing sample v473l for Ventricular_Tachycardia: index 152 is out of bounds for axis 0 with size 61
Error processing sample v475l for Ventricular_Tachycardia: index 153 is out of bounds for axis 0 with size 61
Error processing sample v476s for Ventricular_Tachycardia: index 154 is out of bounds for axis 0 with size 61
Error processing sample v481l for Ventricular_Tachycardia: index 155 is out of bounds for axis 0 with size 61
Error processing sample v482s for Ventricular_Tachycardia: index 156 is out of bounds for axis 0 with size 61
Error processing sample v483l for Ventricular_Tachycardia: index 157 is out of bounds for axis 0 with size 61
Error processing sample v489l for Ventricular_Tachycardia: index 158 is out of bounds for axis 0 with size 61
Error processing sample v491l for Ventricular_Tachycardia: index 159 is out of bounds for axis 0 with size 61
Error processing sample v492s for Ventricular_Tachycardia: index 160 is out of bounds for axis 0 with size 61
Error processing sample v498s for Ventricular_Tachycardia: index 161 is out of bounds for axis 0 with size 61
Error processing sample v501l for Ventricular_Tachycardia: index 162 is out of bounds for axis 0 with size 61
Error processing sample v502s for Ventricular_Tachycardia: index 163 is out of bounds for axis 0 with size 61
Error processing sample v505l for Ventricular_Tachycardia: index 164 is out of bounds for axis 0 with size 61
Error processing sample v510s for Ventricular_Tachycardia: index 165 is out of bounds for axis 0 with size 61
Error processing sample v511l for Ventricular_Tachycardia: index 166 is out of bounds for axis 0 with size 61
Error processing sample v513l for Ventricular_Tachycardia: index 167 is out of bounds for axis 0 with size 61
Error processing sample v518s for Ventricular_Tachycardia: index 168 is out of bounds for axis 0 with size 61
Error processing sample v519l for Ventricular_Tachycardia: index 169 is out of bounds for axis 0 with size 61
Error processing sample v525l for Ventricular_Tachycardia: index 170 is out of bounds for axis 0 with size 61
Error processing sample v531l for Ventricular_Tachycardia: index 171 is out of bounds for axis 0 with size 61
Error processing sample v532s for Ventricular_Tachycardia: index 172 is out of bounds for axis 0 with size 61
Error processing sample v533l for Ventricular_Tachycardia: index 173 is out of bounds for axis 0 with size 61
Error processing sample v534s for Ventricular_Tachycardia: index 174 is out of bounds for axis 0 with size 61
Error processing sample v535l for Ventricular_Tachycardia: index 175 is out of bounds for axis 0 with size 61
Error processing sample v536s for Ventricular_Tachycardia: index 176 is out of bounds for axis 0 with size 61
Error processing sample v540s for Ventricular_Tachycardia: index 177 is out of bounds for axis 0 with size 61
Error processing sample v541l for Ventricular_Tachycardia: index 178 is out of bounds for axis 0 with size 61
Error processing sample v542s for Ventricular_Tachycardia: index 179 is out of bounds for axis 0 with size 61
Error processing sample v548s for Ventricular_Tachycardia: index 180 is out of bounds for axis 0 with size 61
Error processing sample v549l for Ventricular_Tachycardia: index 181 is out of bounds for axis 0 with size 61
Error processing sample v551l for Ventricular_Tachycardia: index 182 is out of bounds for axis 0 with size 61
Error processing sample v552s for Ventricular_Tachycardia: index 183 is out of bounds for axis 0 with size 61
Error processing sample v557l for Ventricular_Tachycardia: index 184 is out of bounds for axis 0 with size 61
Error processing sample v559l for Ventricular_Tachycardia: index 185 is out of bounds for axis 0 with size 61
Error processing sample v564s for Ventricular_Tachycardia: index 186 is out of bounds for axis 0 with size 61
Error processing sample v566s for Ventricular_Tachycardia: index 187 is out of bounds for axis 0 with size 61
Error processing sample v568s for Ventricular_Tachycardia: index 188 is out of bounds for axis 0 with size 61
Error processing sample v569l for Ventricular_Tachycardia: index 189 is out of bounds for axis 0 with size 61
Error processing sample v570s for Ventricular_Tachycardia: index 190 is out of bounds for axis 0 with size 61
Error processing sample v571l for Ventricular_Tachycardia: index 191 is out of bounds for axis 0 with size 61
Error processing sample v573l for Ventricular_Tachycardia: index 192 is out of bounds for axis 0 with size 61
Error processing sample v574s for Ventricular_Tachycardia: index 193 is out of bounds for axis 0 with size 61
Error processing sample v575l for Ventricular_Tachycardia: index 194 is out of bounds for axis 0 with size 61
Error processing sample v581l for Ventricular_Tachycardia: index 195 is out of bounds for axis 0 with size 61
Error processing sample v583l for Ventricular_Tachycardia: index 196 is out of bounds for axis 0 with size 61
Error processing sample v590s for Ventricular_Tachycardia: index 197 is out of bounds for axis 0 with size 61
Error processing sample v597l for Ventricular_Tachycardia: index 198 is out of bounds for axis 0 with size 61
Error processing sample v598s for Ventricular_Tachycardia: index 199 is out of bounds for axis 0 with size 61

/var/folders/87/1x2ps50d7dx1y569r31__0t00000gn/T/ipykernel_15915/973443539.py:4: RuntimeWarning: invalid value encountered in divide
  return ( data - np.mean(data) ) / np.std(data)
/var/folders/87/1x2ps50d7dx1y569r31__0t00000gn/T/ipykernel_15915/973443539.py:4: RuntimeWarning: invalid value encountered in divide
  return ( data - np.mean(data) ) / np.std(data)

Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t506s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t507l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t508s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t509l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t520s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t521l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t524s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t546s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t547l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t565l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t567l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t577l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t580s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t589l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t595l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t614s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t622s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t662s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t665l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t678s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t679l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t680s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t683l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t688s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t689l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t693l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t698s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t700s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t716s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t717l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t731l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t737l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t739l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t741l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t742s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t744s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t745l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t747l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t752s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t755l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t760s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t762s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t771l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t786s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t787l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t790s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Tachycardia/t800s.csv
Error processing sample t801l for Tachycardia: index 108 is out of bounds for axis 0 with size 108
Error processing sample t812s for Tachycardia: index 109 is out of bounds for axis 0 with size 108
Error processing sample t816s for Tachycardia: index 110 is out of bounds for axis 0 with size 108
Error processing sample t817l for Tachycardia: index 111 is out of bounds for axis 0 with size 108
Error processing sample t821l for Tachycardia: index 112 is out of bounds for axis 0 with size 108
Processing Bradycardia samples. Number of samples: 77
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b124s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b125l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b126s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b183l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b184s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b187l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b215l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b216s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b220s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b227l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b228s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b229l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b231l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b265l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b269l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b299l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b308s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b313l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b314s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b330s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b331l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b332s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b339l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b340s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b341l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b379l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b387l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b388s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b389l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b428s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b451l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b455l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b456s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b484s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b485l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b486s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b487l.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b488s.csv
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Bradycardia/b497l.csv
Error processing sample b515l for Bradycardia: index 39 is out of bounds for axis 0 with size 39
Error processing sample b516s for Bradycardia: index 40 is out of bounds for axis 0 with size 39
Error processing sample b517l for Bradycardia: index 41 is out of bounds for axis 0 with size 39
Error processing sample b528s for Bradycardia: index 42 is out of bounds for axis 0 with size 39
Error processing sample b537l for Bradycardia: index 43 is out of bounds for axis 0 with size 39
Error processing sample b538s for Bradycardia: index 44 is out of bounds for axis 0 with size 39
Error processing sample b553l for Bradycardia: index 45 is out of bounds for axis 0 with size 39
Error processing sample b554s for Bradycardia: index 46 is out of bounds for axis 0 with size 39
Error processing sample b560s for Bradycardia: index 47 is out of bounds for axis 0 with size 39
Error processing sample b561l for Bradycardia: index 48 is out of bounds for axis 0 with size 39
Error processing sample b562s for Bradycardia: index 49 is out of bounds for axis 0 with size 39
Error processing sample b587l for Bradycardia: index 50 is out of bounds for axis 0 with size 39
Error processing sample b588s for Bradycardia: index 51 is out of bounds for axis 0 with size 39
Error processing sample b600s for Bradycardia: index 52 is out of bounds for axis 0 with size 39
Error processing sample b617l for Bradycardia: index 53 is out of bounds for axis 0 with size 39
Error processing sample b656s for Bradycardia: index 54 is out of bounds for axis 0 with size 39
Error processing sample b659l for Bradycardia: index 55 is out of bounds for axis 0 with size 39
Error processing sample b664s for Bradycardia: index 56 is out of bounds for axis 0 with size 39
Error processing sample b669l for Bradycardia: index 57 is out of bounds for axis 0 with size 39
Error processing sample b672s for Bradycardia: index 58 is out of bounds for axis 0 with size 39
Error processing sample b681l for Bradycardia: index 59 is out of bounds for axis 0 with size 39
Error processing sample b684s for Bradycardia: index 60 is out of bounds for axis 0 with size 39
Error processing sample b685l for Bradycardia: index 61 is out of bounds for axis 0 with size 39
Error processing sample b695l for Bradycardia: index 62 is out of bounds for axis 0 with size 39
Error processing sample b703l for Bradycardia: index 63 is out of bounds for axis 0 with size 39
Error processing sample b706s for Bradycardia: index 64 is out of bounds for axis 0 with size 39
Error processing sample b730s for Bradycardia: index 65 is out of bounds for axis 0 with size 39
Error processing sample b734s for Bradycardia: index 66 is out of bounds for axis 0 with size 39
Error processing sample b753l for Bradycardia: index 67 is out of bounds for axis 0 with size 39
Error processing sample b764s for Bradycardia: index 68 is out of bounds for axis 0 with size 39
Error processing sample b794s for Bradycardia: index 69 is out of bounds for axis 0 with size 39
Error processing sample b820s for Bradycardia: index 70 is out of bounds for axis 0 with size 39
Error processing sample b832s for Bradycardia: index 71 is out of bounds for axis 0 with size 39
Error processing sample b835l for Bradycardia: index 72 is out of bounds for axis 0 with size 39
Error processing sample b838s for Bradycardia: index 73 is out of bounds for axis 0 with size 39
Error processing sample b839l for Bradycardia: index 74 is out of bounds for axis 0 with size 39
Error processing sample b840s for Bradycardia: index 75 is out of bounds for axis 0 with size 39
Error processing sample b849l for Bradycardia: index 76 is out of bounds for axis 0 with size 39
Processing Atrial_Fibrillation samples. Number of samples: 19
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_017_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_017_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Atrial_Fibrillation/af_017.csv
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_016_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_016_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Atrial_Fibrillation/af_016.csv
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_001_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_001_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Atrial_Fibrillation/af_001.csv
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_007_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_007_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Atrial_Fibrillation/af_007.csv
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_006_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_006_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Atrial_Fibrillation/af_006.csv
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_010_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_010_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Atrial_Fibrillation/af_010.csv
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_011_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_011_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Atrial_Fibrillation/af_011.csv
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_009_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_009_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Atrial_Fibrillation/af_009.csv
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_008_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_008_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Atrial_Fibrillation/af_008.csv
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_003_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_003_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Atrial_Fibrillation/af_003.csv
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_002_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_002_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Atrial_Fibrillation/af_002.csv
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_014_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_014_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
Saved to /Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/arrhythmia_data/folder/Atrial_Fibrillation/af_014.csv
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_015_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.
/Users/sarahalabdulrazzak/Desktop/Capstone/myenv/Data/mimic_perform_af_csv/mimic_perform_af_015_data.csv: Original sampling rate = 125 Hz
  Signal is already at 125 Hz — no resampling needed.